// See https://aka.ms/new-console-template for more information
Judge simonCowell = new Judge("Simon Cowell");
Singer ladyGaga = new Singer("Lady Gaga", "Pop", Singer.VocalRange.Alt);
Singer christinaAguilera = new Singer("Christina Aguilera", "Pop", Singer.VocalRange.Soprano);

Song gaga1 = new Song("Shallow", "Tell me something, girl\r\nAre you happy in this modern world?\r\nOr do you need more?\r\nIs there something else you're searchin' for?\r\nI'm falling\r\nIn all the good times, I find myself longin' for change\r\nAnd in the bad times, I fear myself\r\nTell me something, boy\r\nAren't you tired trying to fill that void?\r\nOr do you need more?\r\nAin't it hard keeping it so hardcore?\r\nI'm falling\r\nIn all the good times, I find myself longing for change\r\nAnd in the bad times, I fear myself\r\nI'm off the deep end, watch as I dive in\r\nI'll never meet the ground\r\nCrash through the surface, where they can't hurt us\r\nWe're far from the shallow now\r\nIn the sha-ha, sha-ha-llow\r\nIn the sha-ha-sha-la-la-la-llow\r\nIn the sha-ha, sha-ha-llow\r\nWe're far from the shallow now\r\nOh, ha-ah-ah\r\nAh, ha-ah-ah, oh, ah\r\nHa-ah-ah-ah\r\nI'm off the deep end, watch as I dive in\r\nI'll never meet the ground\r\nCrash through the surface, where they can't hurt us\r\nWe're far from the shallow now\r\nIn the sha-ha, sha-ha-llow\r\nIn the sha-ha-sha-la-la-la-llow\r\nIn the sha-ha, sha-ha-llow\r\nWe're far from the shallow now");
Song gaga2 = new Song("Just Dance", "RedOne, Konvict\r\nGaGa, oh, eh\r\nI've had a little bit too much, much (oh, oh, oh)\r\nAll of the people start to rush (start to rush by)\r\nA dizzy twister dance, can't find my drink or man\r\nWhere are my keys? I lost my phone, phone (oh, oh, oh)\r\nWhat's goin' on on the floor?\r\nI love this record, baby, but I can't see straight anymore (woo!)\r\nKeep it cool, what's the name of this club?\r\nI can't remember but it's alright, a-alright\r\nJust dance, gonna be okay, da da doo-doo-mmm\r\nJust dance, spin that record, babe, da da doo-doo-mmm\r\nJust dance, gonna be okay, d-d-d-dance\r\nDance, dance, just, j-j-just dance\r\nWish I could shut my playboy mouth (oh, oh, oh)\r\nHow'd I turn my shirt inside out? (Inside out, right)\r\nControl your poison, babe, roses have thorns, they say\r\nAnd we're all gettin' hosed tonight (oh, oh, oh)\r\nWhat's goin' on on the floor?\r\nI love this record, baby, but I can't see straight anymore\r\nKeep it cool, what's the name of this club?\r\nI can't remember but it's alright, a-alright (woo!)\r\nJust dance, gonna be okay, da da doo-doo-mmm\r\nJust dance, spin that record, babe, da da doo-doo-mmm\r\nJust dance, gonna be okay, d-d-d-dance\r\nDance, dance, just, j-j-just\r\nWhen I come through on the dance floor checkin' out that catalog (hey)\r\nCan't believe my eyes, so many women without a flaw (hey)\r\nAnd I ain't gon' give it up, steady tryna pick it up like a call (hey)\r\nI'ma hit it, I'ma beat it and flex and do it until tomorr' yeah\r\nShawty I can see that you got so much energy\r\nThe way you're twirlin' up them hips 'round and 'round\r\nAnd now there's no reason at all why you can't leave here with me\r\nIn the meantime stay and let me watch you break it down\r\nAnd dance, gonna be okay (oh) da da doo-doo-mmm\r\nJust dance (ooh yeah), spin that record babe, da da doo-doo-mmm\r\nJust dance (ooh yeah), gonna be okay, da da doo-doo-mmm\r\nJust dance (ooh yeah), spin that record babe, da da doo-doo-mmm\r\nJust dance (oh), gonna be okay, d-d-d-dance (gonna be okay)\r\nDance, dance (yeah)\r\nJust, j-j-just dance (oh)\r\nWoo! let's go!\r\nHalf psychotic, sick, hypnotic\r\nGot my blueprint, it's symphonic\r\nHalf psychotic, sick, hypnotic\r\nGot my blueprint electronic\r\nHalf psychotic, sick, hypnotic\r\nGot my blueprint, it's symphonic\r\nHalf psychotic, sick, hypnotic\r\nGot my blueprint electronic\r\nGo!\r\nUse your muscle, carve it out, work it, hustle\r\nI got it, just stay close enough to get it on\r\nDon't slow!\r\nDrive it, clean it, lights out, bleed it, spend the lasto\r\nI got it\r\nIn your pocko\r\nI got it\r\nJust dance, gonna be okay, da da doo-doo-mmm\r\nJust dance, spin that record babe, da da doo-doo-mmm\r\nJust dance (baby), gonna be okay, da da doo-doo-mmm\r\nJust dance, spin that record babe, da da doo-doo-mmm (baby, yeah)\r\nJust dance, gonna be okay, d-d-d-dance (spin that record, baby, yeah)\r\nDance, dance, just, j-j-just dance");
Song christina1 = new Song("Beautiful", "Don't look at me\r\nEvery day is so wonderful\r\nThen suddenly it's hard to breathe\r\nNow and then I get insecure\r\nFrom all the pain\r\nI'm so ashamed\r\nI am beautiful no matter what they say\r\nWords can't bring me down\r\nI am beautiful in every single way\r\nYes, words can't bring me down, oh no\r\nSo don't you bring me down today\r\nTo all your friends you're delirious\r\nSo consumed in all your doom\r\nTrying hard to fill the emptiness\r\nThe pieces gone, left the puzzle undone\r\nIs that the way it is?\r\nYou are beautiful no matter what they say\r\nWords can't bring you down, oh no\r\nYou are beautiful in every single way\r\nYes, words can't bring you down, oh no\r\nSo don't you bring me down today\r\nNo matter what we do\r\n(No matter what we do)\r\nNo matter what we say\r\n(No matter what we say)\r\nWe're the song inside the tune (Yeah)\r\nFull of beautiful mistakes\r\nAnd everywhere we go\r\n(And everywhere we go)\r\nThe sun will always shine\r\n(The sun will always, always shine)\r\nAnd tomorrow we might wake on the other side\r\n'Cause we are beautiful no matter what they say\r\nYes, words won't bring us down, no, no\r\nWe are beautiful in every single way\r\nYes, words can't bring us down, oh, no\r\nSo don't you bring me down today\r\nOoh-oh-oh, yeah\r\nDon't you bring me down today\r\nYeah, ooh\r\nDon't you bring me down\r\nOoh, today");

ladyGaga.AddSong(gaga1);
ladyGaga.AddSong(gaga2);
christinaAguilera.AddSong(christina1);

Console.WriteLine("Welcome to the greatest most important song contest that has ever happened!!! MAMAS IDOL \n");
ladyGaga.Perform();
simonCowell.JudgePerformance();
christinaAguilera.Perform();
simonCowell.JudgePerformance();
simonCowell.ChooseWinner(ladyGaga, christinaAguilera);
Console.ReadLine();
